### ISSUE TITLE
A couple problems, a suggestion, and a question

### ISSUE THREAD

**Issue by IdrisQe** [Jolkert/deselect#1]
Hi, first of all, I just want to say _**THANK YOU SO MUCH**_
I have been _praying_ (metaphorically) that someone would release a mod that does exactly this for over half a decade now, especially given how many mods require you to interact with things with an empty hand; I even tried figuring out how to write it myself multiple times but couldn't figure it out. Looking at your code, I can't believe how much I was overcomplicating it.

That said, I have noticed a couple issues in my early testing:

1. The hotbar selector still renders, offset weirdly. This is mainly visible on smaller GUI Scales. The hotbar selector will render way off to the left of the hotbar, presumably since it's offset by slot number, and slot... -7 is being used if I recall right?
My modding knowledge is extremely limited, but I assume the best way to fix this would probably be to hook into the hotbar renderer and stop the selector from showing when the negative slot is utilized. A more hacky way would be to just use a much larger negative slot and hope that the selector renders offscreen no matter the GUI size.
See (Screen snip taken at 1920x1080, on a maximized game window with GUI Scale 2):
![image](https://github.com/user-attachments/assets/40b1eb4a-acfc-4437-9b72-5d939682288d)

2. Processes that force an item into your hand crash the game. I haven't tested with other mods that put things directly into your hand, but I confirmed this occuring with Pick Block in Creative Mode. Trying to use the Pick Block Hotkey while "deselected" instantly crashed me to desktop. I assume it's because the slot isn't a "real" slot, so the game panics trying to put an item there. Probably more complicated to fix without causing other problems like the deselection slot getting filled with items.
See (Minecraft 1.20.1, Fabric Loader 0.16.5, Fabric API 0.92.2):
```
[15:37:57] [Render thread/ERROR]: Unreported exception thrown!
java.lang.ArrayIndexOutOfBoundsException: Index -7 out of bounds for length 36
	at java.util.Arrays$ArrayList.get(Arrays.java:4165) ~[?:?]
	at net.minecraft.class_2371.get(class_2371.java:47) ~[client-intermediary.jar:?]
	at net.minecraft.class_1661.method_7386(class_1661.java:150) ~[client-intermediary.jar:?]
	at net.minecraft.class_1661.method_7374(class_1661.java:92) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1511(class_310.java:2363) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1508(class_310.java:2055) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1883) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1181) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.5.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
[15:37:57] [Server thread/INFO]: Stopping server
[15:37:57] [Server thread/INFO]: Saving players
[15:37:57] [Server thread/INFO]: Saving worlds
[15:37:58] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[15:37:58] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[15:37:58] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[15:37:58] [Server thread/INFO]: ThreadedAnvilChunkStorage (New World): All chunks are saved
[15:37:58] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[15:37:58] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[15:37:58] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2024-09-07 15:37:58
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: Index -7 out of bounds for length 36
	at java.base/java.util.Arrays$ArrayList.get(Arrays.java:4165)
	at net.minecraft.class_2371.get(class_2371.java:47)
	at net.minecraft.class_1661.method_7386(class_1661.java:150)
	at net.minecraft.class_1661.method_7374(class_1661.java:92)
	at net.minecraft.class_310.method_1511(class_310.java:2363)
	at net.minecraft.class_310.method_1508(class_310.java:2055)
	at net.minecraft.class_310.method_1574(class_310.java:1883)
	at net.minecraft.class_310.method_1523(class_310.java:1181)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.Arrays$ArrayList.get(Arrays.java:4165)
	at net.minecraft.class_2371.get(class_2371.java:47)
	at net.minecraft.class_1661.method_7386(class_1661.java:150)
	at net.minecraft.class_1661.method_7374(class_1661.java:92)
	at net.minecraft.class_310.method_1511(class_310.java:2363)
	at net.minecraft.class_310.method_1508(class_310.java:2055)

-- Affected level --
Details:
	All players: 1 total; [class_746['HickoryHazelyPip'/1, l='ClientLevel', x=10.99, y=-60.00, z=8.35]]
	Chunk stats: 961, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1040 game time, 1040 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```
3. Pressing the Swap Hands Hotkey while deselected seems to delete your offhand item. Attempting to left or right click on a block after doing this will crash the game.
See: Swapping Hands Error Message:
```
[16:13:38] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2846@41f113a, suppressing error
java.lang.ArrayIndexOutOfBoundsException: Index -16 out of bounds for length 36
	at java.util.Arrays$ArrayList.set(Arrays.java:4170) ~[?:?]
	at net.minecraft.class_2371.set(class_2371.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.class_1657.method_5673(class_1657.java:1966) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_6122(class_1309.java:1951) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_12066(class_3244.java:1063) ~[client-intermediary.jar:?]
	at net.minecraft.class_2846.method_12361(class_2846.java:42) ~[client-intermediary.jar:?]
	at net.minecraft.class_2846.method_11054(class_2846.java:8) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[16:13:40] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2846@9d7aea8, suppressing error
java.lang.ArrayIndexOutOfBoundsException: Index -16 out of bounds for length 36
	at java.util.Arrays$ArrayList.set(Arrays.java:4170) ~[?:?]
	at net.minecraft.class_2371.set(class_2371.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.class_1657.method_5673(class_1657.java:1966) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_6122(class_1309.java:1951) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_12066(class_3244.java:1063) ~[client-intermediary.jar:?]
	at net.minecraft.class_2846.method_12361(class_2846.java:42) ~[client-intermediary.jar:?]
	at net.minecraft.class_2846.method_11054(class_2846.java:8) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```
and the crash when trying to interact with a block afterward:
```
[16:13:59] [Render thread/ERROR]: Unreported exception thrown!
java.lang.ArrayIndexOutOfBoundsException: Index -16 out of bounds for length 36
	at java.util.Arrays$ArrayList.get(Arrays.java:4165) ~[?:?]
	at net.minecraft.class_2371.get(class_2371.java:47) ~[client-intermediary.jar:?]
	at net.minecraft.class_1661.method_7370(class_1661.java:413) ~[client-intermediary.jar:?]
	at net.minecraft.class_1657.method_7351(class_1657.java:758) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970.method_9594(class_4970.java:389) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26165(class_4970.java:997) ~[client-intermediary.jar:?]
	at net.minecraft.class_636.method_41930(class_636.java:180) ~[client-intermediary.jar:?]
	at net.minecraft.class_636.method_41931(class_636.java:278) ~[client-intermediary.jar:?]
	at net.minecraft.class_636.method_2910(class_636.java:175) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1536(class_310.java:1736) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1508(class_310.java:2049) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1883) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1181) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.5.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
```

I also have a suggestion- it would be nice if scrolling backward when on slot 1 or scrolling forward when on slot 9 would put you in the deselected mode, and then scrolling either way would put you on the expected slot. So If you're on slot 8 and you scroll right 3 times it would go 8 > 9 > Deselected > 1 - basically just integrating it as a scrollable slot for people who like that. Could even have a config option for it in case people don't want it.

And one last thing - would you be okay with it if I were to attempt to port this to NeoForge? I doubt anything will come of it given my aforementioned lack of modding prowess, but this is something both modloaders would make great use of.

**Comment by Jolkert** [comment]
## Preface
*(Ok so "preface" makes this sound overly formal. It's just kinda the best word for the job)*

I'm glad I'm not the only one! Ever since I played Starbound I've been wanting this functionality in Minecraft (personally, primarily for atmosphere purposes of not having to shuffle around hotbar slots just to walk around my home with an empty hand), and when I realized no one else was gonna do it, I decided I'd just do it myself lol.

Thank you very much for taking interest and bringing these things to my attention. I wasn't really sure what edge cases to check for while developing, but I *knew* something was gonna break. I just haven't played with it in an actual world yet, so I never quite got a feel for it.

## On the bugs
### Issue 1
Yeah I knew right away that this was gonna be an issue. I saw that the vanilla code uses `-1` as a sentinel value for certain operations and figured `-1` was not gonna be an option, so the first thing I thought of was `-2`. Turns out, that was also a bad call, since a hotbar slot just rendered a little farther out. I then tried `Integer.MIN_VALUE`, but for some reason that caused the slot to render *in* the hotbar? (I haven't looked at the rendering code properly, but it seems like there might be some wrapping going on?). Setting it to `-16` seemed to work fine on my resolution + preferred gui scale, but I did have the suspicion that higher res displays or lower gui scales would break that. Seems I was right. My goal is to mix into as few places as I can, so I will see what I can do with just negative hotbar values, but you might be right that mixing into the rendering directly might be the best way about it.
### Issue 2
This should be an easy fix? There are two ways about it
1) snap the hotbar back to the previously selected slot on pickblock
1) disable pickblock while deselected  

Personally, I would absolutely choose option 1 every time, but I'm curious to see if you might have a different opinion on that one.
### Issue 3
This should be basically the same process to fix as the above

## On the suggestion
Personally, *I* would not like or use that feature, but I am certainly willing to make it a config option for anyone who might like that!

## On the question
I personally have no plans to learn (Neo)Forge, so I am perfectly fine with you porting it to the Forge ecosystem. If you need any help with anything, feel free to contact me on Discord (I am `jolkert` there as well) either by sending me a friend request or just joining [my server](https://discord.gg/G3pqGwydVd) (shameless plug)

## Postface[<sup>[it's real]</sup>](https://en.wiktionary.org/wiki/postface)
I am busy this weekend and on monday, so I won't have much time to work on bugfixes until tuesday, but the fixes should be pretty quick to bang out once I get time to sit down and actually write the thing (famous last words).

To be fully honest, I'm astonished that the mod does what it's meant to even at all with how thoroughly my solution is just a complete bodge lol. If any more issues come up, please feel free to toss them my way, and I'll make sure they're taken care of!

**Comment by Jolkert** [comment]
As of version 1.1.1 (commit 666a56b), this issue all three issues mentioned in this post have been resolved!

I'll begin work on your suggestion soon, but I will close the issue. If you have any other problems or suggestions, feel free to create a new issue or reach out on discord!

**Comment by IdrisQe** [comment]
> ## Preface
> 
> _(Ok so "preface" makes this sound overly formal. It's just kinda the best word for the job)_
Don't worry, I get it, I tend to be overly formal when writing bug reports and the like anyway!

> I'm glad I'm not the only one! Ever since I played Starbound I've been wanting this functionality in Minecraft (personally, primarily for atmosphere purposes of not having to shuffle around hotbar slots just to walk around my home with an empty hand), and when I realized no one else was gonna do it, I decided I'd just do it myself lol.

Me too! I'm glad they kept that functionality even after they butchered the hotbar in one of the last betas before release _(yes I am still salty about that)_
There have been a couple mods in the past which would hide your held item and show your hand instead, but it still counted as holding the item, or required a special glove item to do so, taking up a slot anyway, and they were usually left on a single obscure version, so when I saw this my eyes lit up like a kid in a candy store!

> Yeah I knew right away that this was gonna be an issue. I saw that the vanilla code uses `-1` as a sentinel value for certain operations and figured `-1` was not gonna be an option, so the first thing I thought of was `-2`. Turns out, that was also a bad call, since a hotbar slot just rendered a little farther out. I then tried `Integer.MIN_VALUE`, but for some reason that caused the slot to render _in_ the hotbar? (I haven't looked at the rendering code properly, but it seems like there might be some wrapping going on?). Setting it to `-16` seemed to work fine on my resolution + preferred gui scale, but I did have the suspicion that higher res displays or lower gui scales would break that. Seems I was right. My goal is to mix into as few places as I can, so I will see what I can do with just negative hotbar values, but you might be right that mixing into the rendering directly might be the best way about it.

>As of version 1.1.1 (commit https://github.com/Jolkert/deselect/commit/666a56b45d9fc9f5b453881671a8e87bd1593c2b), this issue all three issues mentioned in this post have been resolved!

I definitely understand wanting to limit how many parts of the code you mess with. I'm glad to know you found a solution though!

> This should be an easy fix? There are two ways about it
> 
>     1. snap the hotbar back to the previously selected slot on pickblock
> 
>     2. disable pickblock while deselected
> 
> Personally, I would absolutely choose option 1 every time, but I'm curious to see if you might have a different opinion on that one.

Oh, definitely option 1. I wonder, is it possible to automatically do that any time an item attempts to enter that slot? Since that would fix more than just pick-block, in case other mods do weird item-forcing things. Unsure if there's a way to pre-emptively detect an item trying to enter the slot before it does so regardless of cause though.

> Personally, _I_ would not like or use that feature, but I am certainly willing to make it a config option for anyone who might like that!

I appreciate it a lot! It's always nice to see developers who will add options that others want, even if they wouldn't use it themselves. Had some irritating interactions in the past with devs who wouldn't even make accessibility options on request >_>

> I personally have no plans to learn (Neo)Forge, so I am perfectly fine with you porting it to the Forge ecosystem. If you need any help with anything, feel free to contact me on Discord (I am `jolkert` there as well) either by sending me a friend request or just joining [my server](https://discord.gg/G3pqGwydVd) (shameless plug)

Thank you for the offer! I'm a bit of a nervous wreck about joining servers but if I need help at some point I might consider poking you! (Be glad I'm not as zealous with questions as I was back in my Roblox days... I used to pester one of my favourite scripters almost daily with questions while digging through his code)
If I do port it sometime successfully, I'll be sure to credit you appropriately on uploading! (Or I might just send it as a pull request so both loaders can be uploaded in one place?)

> ## Postface[[it's real]](https://en.wiktionary.org/wiki/postface)

...Thank you for the new word. I'm _absolutely_ going to start using this! (if I remember to)

> I am busy this weekend and on monday, so I won't have much time to work on bugfixes until tuesday, but the fixes should be pretty quick to bang out once I get time to sit down and actually write the thing (famous last words).
> 
> To be fully honest, I'm astonished that the mod does what it's meant to even at all with how thoroughly my solution is just a complete bodge lol. If any more issues come up, please feel free to toss them my way, and I'll make sure they're taken care of!

That's fine, real life priorities should always come first! Besides, I admittedly haven't been playing modded Minecraft much lately, so haven't tested the update yet. Only made an instance to test your mod because I got extremely excited to see someone actually made this mod- but it's made me want to play again!
And hey, sometimes the simple solution is the right solution, and sometimes the jank solution is the best solution!

Thank you again for taking the time for such a thorough response, on top of taking my bugs, suggestion, and questions all seriously!



Edit: Oh yeah, one more suggestion I forgot about - If I recall right Starbound worked like this too? It's been so many years since I played that I don't quite recall, but I think it did? - maybe a config option where if you press the hotkey of your currently selected item it would swap to the empty slot? (So if you have slot 1 selected and press 1, it would go to the empty slot. If you had 5 selected and pressed 5, etc.)
